/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedReposIndexRouteImport } from './routes/_authed.repos.index'
import { Route as AuthedReposOwnerRepoIndexRouteImport } from './routes/_authed.repos.$owner.$repo.index'
import { Route as AuthedReposOwnerRepoEditSplatRouteImport } from './routes/_authed.repos.$owner.$repo.edit.$'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReposIndexRoute = AuthedReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReposOwnerRepoIndexRoute =
  AuthedReposOwnerRepoIndexRouteImport.update({
    id: '/repos/$owner/$repo/',
    path: '/repos/$owner/$repo/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedReposOwnerRepoEditSplatRoute =
  AuthedReposOwnerRepoEditSplatRouteImport.update({
    id: '/repos/$owner/$repo/edit/$',
    path: '/repos/$owner/$repo/edit/$',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/repos/': typeof AuthedReposIndexRoute
  '/repos/$owner/$repo/': typeof AuthedReposOwnerRepoIndexRoute
  '/repos/$owner/$repo/edit/$': typeof AuthedReposOwnerRepoEditSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/repos': typeof AuthedReposIndexRoute
  '/repos/$owner/$repo': typeof AuthedReposOwnerRepoIndexRoute
  '/repos/$owner/$repo/edit/$': typeof AuthedReposOwnerRepoEditSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authed/repos/': typeof AuthedReposIndexRoute
  '/_authed/repos/$owner/$repo/': typeof AuthedReposOwnerRepoIndexRoute
  '/_authed/repos/$owner/$repo/edit/$': typeof AuthedReposOwnerRepoEditSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/repos/'
    | '/repos/$owner/$repo/'
    | '/repos/$owner/$repo/edit/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/repos'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/edit/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/_authed/repos/'
    | '/_authed/repos/$owner/$repo/'
    | '/_authed/repos/$owner/$repo/edit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/repos/': {
      id: '/_authed/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof AuthedReposIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repos/$owner/$repo/': {
      id: '/_authed/repos/$owner/$repo/'
      path: '/repos/$owner/$repo'
      fullPath: '/repos/$owner/$repo/'
      preLoaderRoute: typeof AuthedReposOwnerRepoIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repos/$owner/$repo/edit/$': {
      id: '/_authed/repos/$owner/$repo/edit/$'
      path: '/repos/$owner/$repo/edit/$'
      fullPath: '/repos/$owner/$repo/edit/$'
      preLoaderRoute: typeof AuthedReposOwnerRepoEditSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedReposIndexRoute: typeof AuthedReposIndexRoute
  AuthedReposOwnerRepoIndexRoute: typeof AuthedReposOwnerRepoIndexRoute
  AuthedReposOwnerRepoEditSplatRoute: typeof AuthedReposOwnerRepoEditSplatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedReposIndexRoute: AuthedReposIndexRoute,
  AuthedReposOwnerRepoIndexRoute: AuthedReposOwnerRepoIndexRoute,
  AuthedReposOwnerRepoEditSplatRoute: AuthedReposOwnerRepoEditSplatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
